using System.Collections.Generic;

namespace RentRosterAutomation
{
    // This class contains the data necessary to print a mailbox tenant list,
    // Each building in the complex contains 3 floors of apartments. The documnets
    // generated by Microsoft Word have 3 columns of data, one for each floor.
    class CMailboxListData
    {
        public int AddressStreetNumber { get; private set; }
        public List<CApartment> FirstFloor { get; private set; }
        public List<CApartment> SecondFloor { get; private set; }
        public List<CApartment> ThirdFloor { get; private set; }

        public CMailboxListData(int addressStreetNumber)
        {
            AddressStreetNumber = addressStreetNumber;
        }

        public CMailboxListData(CBuilding building)
        {
            AddressStreetNumber = building.AddressStreetNumber;
            FirstFloor = new List<CApartment>();
            SecondFloor = new List<CApartment>();
            ThirdFloor = new List<CApartment>();
        }

        public void addApartmentData(CApartment apartment)
        {
            if (apartment.ApartmentNumber >= 200 && apartment.ApartmentNumber < 300)
            {
                SecondFloor.Add(apartment);
            }
            else if (apartment.ApartmentNumber >= 300)
            {
                ThirdFloor.Add(apartment);
            }
            else
            {
                FirstFloor.Add(apartment);
            }

        }
    }
}
