using System.Collections.Generic;

namespace TenantRosterAutomation
{
    // This class contains the data necessary to print a mailbox tenant list,
    // Each building in the complex contains 3 floors of apartments. The documnets
    // generated by Microsoft Word have 3 columns of data, one for each floor.
    class MailboxData
    {
        public int AddressStreetNumber { get; private set; }
        public List<Apartment> FirstFloor { get; private set; }
        public List<Apartment> SecondFloor { get; private set; }
        public List<Apartment> ThirdFloor { get; private set; }

        public MailboxData(int addressStreetNumber)
        {
            AddressStreetNumber = addressStreetNumber;
        }

        public MailboxData(Building building)
        {
            AddressStreetNumber = building.AddressStreetNumber;
            FirstFloor = new List<Apartment>();
            SecondFloor = new List<Apartment>();
            ThirdFloor = new List<Apartment>();
        }

        public void addApartmentData(Apartment apartment)
        {
            if (apartment.ApartmentNumber >= 200 && apartment.ApartmentNumber < 300)
            {
                SecondFloor.Add(apartment);
            }
            else if (apartment.ApartmentNumber >= 300)
            {
                ThirdFloor.Add(apartment);
            }
            else
            {
                FirstFloor.Add(apartment);
            }

        }
    }
}
